# --- Autostart ---
exec-once = waybar
exec-once = swaybg -i /home/milkaa/wallpaper/moun.jpeg

monitor = , preferred, auto, 1.25


input {
    kb_layout = fr
    numlock_by_default = true
}

decoration {
    rounding = 10
    blur {
        enabled = true
        size = 8
        passes = 2
        new_optimizations = true
    }
}

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = rgba(ffffffff)
}

# --- Keybinds ---

# Fullscreen
bind = SUPER, F, fullscreen, 1

# Navigation with numeric keypad 0
bind = , KP_Insert, cyclenext,

# Launch app
bind = SUPER, A, exec, radial-menu
bind = SUPER, R, exec, rofi -show drun
bind = SUPER, Q, exec, kitty
bind = SUPER, C, killactive

# Quit Hyprland
bind = SUPER, M, exit